### ISSUE TITLE
[Feature] Allow end users to pass their own LLM API key and LLM model params

### ISSUE THREAD

**Issue by igiloh-pinecone** [pinecone-io/canopy#164]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [ ] I am requesting a straightforward extension of existing functionality

### Describe the feature

We currently designed `canopy-server` and the `LLM` class under the assumption that a developers would build a Chatbot service with Canopy which offers a single bot service. Under that assumption - all the LLM calls are done by a single pre-configured API key, using pre-configured model params (such as `model_name`, `max_generated_tokens`).

However, some developers might want to offer a multi-tenant bot service over the same knowledge base. In that case, the server would need to take the API key and the model params from each individual `/chat.completion` call, and the LLM should allow passing these per call.

### Describe alternatives you've considered

We should probably add a `bool` in the `LLM`'s config which determines whether or not to allow to pass model params per call.  
We can maybe add a separate config flag specifying whether or not to allow users to pass their own personal LLM API keys.

Theoretically, we can even do a more detailed `allow_override` bool per each model param - but that's probably an overkill.

### Who will this benefit?

Developers who want to use Canopy to offer multi-tenant chatbot service.

**Comment by malexw** [comment]
👋 Hi @igiloh-pinecone,

I though I'd take a look at implementing this. Do you have a vision for what this set of changes looks like?

For the most part passing model parameters through looks fairly straightforward to me. Two pain points I see are around handling API keys, or passing model parameters in a world where Canopy supports additional LLMs besides OpenAI. Using the Cohere LLM as an example, their equivalent of `/chat/completions` is just `/generate`. Is the plan for Canopy to expose additional routes in the server that align with the APIs of the other LLMs, or will canopy offer a single combined API route that handles requests that eventually make their way to the appropriate `ChatEngine`?

I notice that both the OpenAI and Cohere python libraries want an API key provided when the client is instantiated. Do you want to go down the path of instantiating appropriate `LLM`s and `ChatEngine`s per-request? Maybe for v1 of these changes it would make sense to continue to use an API key provided by the `config.yaml` or an env var, and just pass the model params?

**Comment by igiloh-pinecone** [comment]
Hi @malexw , thank you for your contribution!!!

The general guidelines we've envisioned so far are:
- Canopy's external API should be OpenAI-like, regardless of the backend LLM class configured (like CohereLLM).
- Only one LLM class should be configured at any given time

Essentially, end users interacting with the canopy Server will always use the /chat/completion API, while the developer configuring the server can switch the backend LLM seamlessly. However, we currently do not plan to allow end users to select a backend LLM per request.

The idea in this issue is allowing end users to send parameters like `max_tokens` and `temperature` per request, then the relevant `LLM` class would convert these to appropriate arguments of the chosen LLM provider.  
The authentication process is less straightforward. For example, the end user would need set his Cohere key inside the `API_key` header of the `/chat/completion` call, which then get passed to `CohereLLM` that will send it in the relevant Cohere headers. We are definitely open for alternative designs for this aspect.

Having said that, we believe most Canopy users will prefer using a single, pre-configured API key (and associated billing account). Therefore, our goal is to keep this use case as simple and intuitive as possible, with advanced features being optional and disabled by default.

**Comment by ishaan-jaff** [comment]
> Canopy's external API should be OpenAI-like, regardless of the backend LLM class configured (like CohereLLM)

Hi @igiloh-pinecone @malexw I'm the maintainer of LiteLLM, we provider an open source proxy to call 100+ LLMs in the OpenAI format
Docs here: https://docs.litellm.ai/docs/simple_proxy 

Hope this is helpful, if not I'd love your feedback on what's missing

**Comment by igiloh-pinecone** [comment]
Done in #191 (disabled by default)
