### ISSUE TITLE
[Bug] Can't create index with fresh instalation

### ISSUE THREAD

**Issue by danielcmm** [pinecone-io/canopy#167]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Just created a new venv, installed canopy, configured the environment variables and when i type canopy new testbase i have the following error:

Error: Failed to create a new index. Reason:
Failed to infer vectors' dimension from encoder due to error: You exceeded your current quota, please check your plan and billing details.. Please fix the error or provide the dimension manually

It happens with the free tier pinecone license and also on the Standard.

### Expected Behavior

Should create the index

### Steps To Reproduce

Env: Windows 11 with miniconda

### Environment

```markdown
- **Windows**:
- **Python 3.11.5**:
- **Canopy cli 0.1.2**:
```

**Comment by danielcmm** [comment]
If anyone has the same issue, the problem was my quota at the openai platform, and not on pinecone. Had to buy more credits. Closed.

**Comment by igiloh-pinecone** [comment]
Thanks @danielcmm!

We'll work on improving the error messages
