### ISSUE TITLE
[Feature] Support for Fine-Tuned Models

### ISSUE THREAD

**Issue by pceulen** [pinecone-io/canopy#174]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

Allow for users to provide details of a fine tuned (OpenAI) model, to replace the default model used by Canopy.

### Describe alternatives you've considered

None.

### Who will this benefit?

Anyone building RAG applications wanting to build both a knowledge base and develop the custom LLM to work with the information. It might avoid the need for very detailed prompts as the current status does require very specific prompting to generate good results.

### Are you interested in contributing this feature?

No

**Comment by miararoy** [comment]
hi @pceulen 

In theory, you should be able to do it today by configuring your Canopy to your model.

The steps you should do are:
1. create a new config file based on the `config.yaml` from [here](https://github.com/pinecone-io/canopy/blob/main/config/config.yaml)
2. under `llm` replace the model name with your finetuned model e.g. `"ft:gpt-3.5-turbo:my-org:custom_suffix:id"`
3. run your canopy server `canopy start --config <PATH_TO_CONFIG_YAML_FILE>`
4. additional, you can set the env var: `CANOPY_CONFIG_FILE` to your path `export CANOPY_CONFIG_FILE=<PATH_TO_CONFIG_YAML_FILE>`
5. Canopy should now use your fine tuned model.

[Source](https://platform.openai.com/docs/guides/fine-tuning/use-a-fine-tuned-model) from OpenAI docs

I am keeping this issue open for visibility, we will try to test this behaviour and make sure this works as expected
