### ISSUE TITLE
[Bug] Uninformative error message when upserting files where UTF-8 file decoding fails

### ISSUE THREAD

**Issue by mjul** [pinecone-io/canopy#181]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When importing a file with canopy-cli (upsert) the `f.read()` in `canopy_cli\data_loader\data_loader.py` can throw a `UnicodeDecodeError` exception. 

This results in the CLI responding with a very uninformative error message like this:

    Error: A unexpected error while loading the data from files in .\data\hello\test.txt. Please make sure the data is in valid `jsonl`, `parquet`, `csv` format or plaintext `.txt` files.

If I patch the code to print out the exception like this, 

            try:
                text = f.read()
            except UnicodeDecodeError as e:
                print("Error reading file: ", e)

It prints the exception message: 

    'charmap' codec can't decode byte 0x9d in position 249: character maps to <undefined>

So, it decoding UTF-8 seems to be the root problem.

### Expected Behavior

Either import the file, handling the error, or provide a better error message so the files can be fixed.

### Steps To Reproduce

I am using Python 3.11 on Windows.

To reproduce create a text file `test.txt` as a UTF-8 encoded text file containing e.g. a 0x9d byte.

`canopy upsert test.txt` then fails:

    Error: A unexpected error while loading the data from files in test.txt. Please make sure the data is in valid `jsonl`, `parquet`, `csv`    format or plaintext `.txt` files.

### Environment

```markdown
- **OS: Windows 11**:
- **Language version: Python 3.11.5**:
- **Canopy version: canopy-sdk==0.1.4**:
```

**Comment by mjul** [comment]
If i change the file `open` in `data_loader.py` line 93 to specify the encoding, e.g. `        with open(file_path, "r", encoding="utf-8") as f:` I can make it read the UTF-8 encoded files, so it appears to somehow select another encoding than UTF-8 for the txt file it is reading.

**Comment by miararoy** [comment]
Hi @mjul !
Thanks for flagging, we internally know our data loading error handling is lacking and I am actively working on a PR for this.

I think utf-8 is good enough for now.

as the PR handles more cases - our specific solution here would be something like:

```python
for file_path in file_paths:
        try:
            with open(file_path, "r", encoding='utf-8') as f:
                text = f.read()
                rows.append(
                    {
                        "id": os.path.basename(file_path).replace(".txt", ""),
                        "text": text,
                        "source": file_path
                    }
                )
        except UnicodeDecodeError as e:
            raise DataLoaderException(
                file_name=file_path,
                row_id="*",
                err="File must be UTF-8 encoded"
            ) from e
```

This implementation is not final but generally it's formatting errors per file/row

What do you think?

**Comment by mjul** [comment]
@miararoy Looks great, I appreciate you working on helping the users find a way forward when things don't work as expected.

**Comment by scottmx81** [comment]
> I can make it read the UTF-8 encoded files, so it appears to somehow select another encoding than UTF-8 for the txt file it is reading (this is an observation, not the suggested solution as it may cause problems for other encodings)

@mjul The standard Python behaviour with the `open` call is to use the value from `locale.getpreferredencoding()` if the encoding is not passed as an argument. It's not a bug per se that it "appears to somehow select another encoding than UTF-8" but rather it is using the default for your platform - which is UTF-8 on macOS and Linux, but not on Windows. On Windows the default encoding would more typically be something like cp850 or cp1252.

As you mentioned, by forcing the encoding to be UTF-8, it could cause errors for other people, when loading files using the default encoding on platforms where UTF-8 is not the default.

It's not a problem that I am having - I just wanted to point out that assuming files are UTF-8 is not the default Python behaviour on Windows.
