### ISSUE TITLE
[Bug] Error on creating new index with canopy new

### ISSUE THREAD

**Issue by coolxeo** [pinecone-io/canopy#183]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

## Command
When I launch the command `canopy new` to create a new index I receive the following error:

```
Error: Failed to create a new index. Reason:
Failed to infer vectors' dimension from encoder due to error: 'ascii' codec can't encode character '\u201c' in position 7: ordinal not in range(128). Please fix the error or provide the dimension manually
```

### Expected Behavior

A new index is created

## Context
- In a fresh installation of canopy
- With a Pinecone account with no indexes
- In Mac Os Sonoma 14.1
- With Python 3.11.4

### Relevant log output

```shell
canopy new
Canopy is going to create a new index: canopy--merchants
Do you want to continue? [y/N]: y
Error: Failed to create a new index. Reason:
Failed to infer vectors' dimension from encoder due to error: 'ascii' codec can't encode character '\u201c' in position 7: ordinal not in range(128). Please fix the error or provide the dimension manually
```
```


### Environment

```markdown
- **OS**: Mac Os Sonoma 14.1
- **Language version**: Python 3.11.4
- **Pinecone client version**: Canopy, version 0.2.0
```

**Comment by igiloh-pinecone** [comment]
Thank you very much @coolxeo for reporting this problem, and apologies for the inconvenience! 

We are  trying to reproduce the problem so we can debug it.  
I'm suspecting this might be locale related, can you please run
```python
import locale
print(locale.getdefaultlocale())
print(locale.getlocale())
```
On the same environment and post the result here?

**Comment by coolxeo** [comment]
@igiloh-pinecone I just found out what it was!
when copying pasting the env variables it copy to my console a strange quote character
`export PINECONE_ENVIRONMENT=“gcp-starter”`
I replaced with the proper one
`export PINECONE_ENVIRONMENT="gcp-starter"`

I saw this before with Mac, apologise for the inconvenient!
