### ISSUE TITLE
[Bug] Command `canopy new` doesn't read config from file specified by environment variable

### ISSUE THREAD

**Issue by MichaelAnckaert** [pinecone-io/canopy#189]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running `canopy new`, the config file specified by the environment variable $CANOPY_CONFIG_FILE is not read. The config file must be manually specified using the `-c` parameter.

### Expected Behavior

The config file specified by $CANOPY_CONFIG_FILE is read.

### Steps To Reproduce

Run `canopy new` 

### Environment

```markdown
- **Canopy version**: master branch
```

**Comment by igiloh-pinecone** [comment]
@MichaelAnckaert thanks for reporting this!

Will be fixed in the next patch release

**Comment by igiloh-pinecone** [comment]
@MichaelAnckaert  sure, go ahead!

**Comment by igiloh-pinecone** [comment]
Resolved by #190
