### ISSUE TITLE
[feature] Support for locally-run vector database

### ISSUE THREAD

**Issue by ThreepE0** [pinecone-io/canopy#196]
Is local vector database support on the roadmap?  Looking for a privacy-focused rag solution, and needing to send all my notes to a cloud service is a deal-breaker for me.

**Comment by igiloh-pinecone** [comment]
Having said that, Canopy is an open source project, and we will of course respect community contributed PRs that would add support to any OSS vector database that is compliant with our testing and code quality standard.
