### ISSUE TITLE
[Bug] CLI - canopy chat not working 

### ISSUE THREAD

**Issue by anada10** [pinecone-io/canopy#207]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I can't use the CLI to do a canopy chat even though I am able to hit the server and conduct chat completion.
<img width="1710" alt="image" src="https://github.com/pinecone-io/canopy/assets/47853125/d82db4da-03c1-4b15-9ad9-a19a265957a4">

### Expected Behavior

CLI to hit server and return chat completion like it did when I manually hit the server
_The range of the Cybertruck is estimated to be between 250-340 miles (400-545 km) according to the EPA. However, with the optional range extender battery, the range can be extended to 440-470 miles (710-755 km).\n(Source: /Users/andrewnada/Downloads/tesla_stats.txt)_

### Steps To Reproduce

1. canopy start
2. canopy upsert the .jsonl below
3. canopy chat --no-rag
4. no result
```
{"id": "0", "text": "Manufacturer Tesla, Inc.", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "1", "text": "Production 2023\u2013present", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "2", "text": "Assembly United States:\u00a0Austin, Texas\u00a0(Gigafactory Texas)", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "3", "text": "Designer Franz von Holzhausen, Sahm\u00a0Jafari,Ian\u00a0Kettle, WooTak\u00a0Kim, Julien\u00a0Bilodeau", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "4", "text": "Body and chassis Class Full-size\u00a0pickup truck Body\u00a0style 4-door\u00a0crew cab Layout Rear motor, rear-wheel drive Dual- or tri-motor, all-wheel drive Powertrain Transmission 1-speed fixed gear ratio", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "5", "text": "Battery 123 kWh: 816 V, 150 Ah +50 kWh (with range extender battery)", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "6", "text": "Electric\u00a0range 250\u2013340\u00a0mi (400\u2013545\u00a0km) EPA estim. 440\u2013470\u00a0mi (710\u2013755\u00a0km) (with optional range extender battery)", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "7", "text": "Plug-in\u00a0charging \u2264250 kW DC at 400V \u2264350 kW DC at 800V 11.5 kW AC (240V, 48A) V2H\u00a0and\u00a0V2V: 11.5 kW AC (240V, 48A) V2L: 9.6 kW AC (240V, 40A) continuous", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "8", "text": "Dimensions Length 223.7\u00a0in (5,680\u00a0mm) Width 80\u201395\u00a0in (2,000\u20132,400\u00a0mm) Height 70.5\u00a0in (1,790\u00a0mm)", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
{"id": "9", "text": "Curb\u00a0weight AWD: 6,603\u00a0lb (2,995\u00a0kg) Cyberbeast: 6,843\u00a0lb (3,104\u00a0kg)", "source": "/Users/andrewnada/Downloads/tesla_stats.txt", "metadata": {}}
```

### Relevant log output

```shell
server is just showing health checks
```

### Environment

```markdown
- **OS**: Mac OS sonoma 14.1.1 (23B81)
- **Language version**: Python 3.11.5
- **Canopy version**: pulled latest f372033
```

**Comment by igiloh-pinecone** [comment]
@anada10 thanks for reporting this!

Are you using the Mac's native Terminal app?  
We know that some Terminals, like the one built into PyCharm don't process the Esc->Enter sequence correctly, and we are working to find a mitigation.  
If you do indeed pressing Esc->Enter like @miararoy have suggested and this still doesn't work - can you please try with Mac's "Terminal" app?

**Comment by anada10** [comment]
Great thanks @igiloh-pinecone @miararoy it was just me not doing the esc + enter combo
Solved now
<img width="559" alt="image" src="https://github.com/pinecone-io/canopy/assets/47853125/33b0212a-2533-434e-a11f-b1d1f33196e8">
