### ISSUE TITLE
[Bug] uninformative error when hitting OpenAI rate limit

### ISSUE THREAD

**Issue by miararoy** [pinecone-io/canopy#218]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

the current behavior is ambiguous error msg:
```Error: Failed to create a new index. Reason:
Failed to infer vectors' dimension from encoder due to error: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please ...
```

### Expected Behavior

The error should indicate that this is the embedding model issue

### Steps To Reproduce

1. change API to random one
2. Try to init a knowledgbase class 

### Environment

```
- **OS**: any
- **Language version**: any
- **Canopy version**: 0.2.0
```

**Comment by igiloh-pinecone** [comment]
Closed by #220, though we will continue improving error handing in the near future, as many other cases are still not covered well
