### ISSUE TITLE
[Namespace] Using namespaces in chat engine

### ISSUE THREAD

**Issue by shubhampatilappy** [pinecone-io/canopy#219]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

from canopy.knowledge_base import KnowledgeBase
kb = KnowledgeBase(index_name="{{TestIndex}}",namespace="{{TestNamespace}}")
kb.connect()

Similar to chain using namespace in vector stores, namespaces should be supported in Chat Engines

### Describe alternatives you've considered

from canopy.knowledge_base import KnowledgeBase
from canopy.chat_engine import ChatEngine
kb = KnowledgeBase(index_name="demo")
kb.connect()
ContextEngine(kb,global_metadata_filter={'key': {'$eq': 'value'}})
chat_engine=ChatEngine(context_engine)

### Who will this benefit?

Balancing costs of using a new index for each set instead of multiple namespaces in an index. Metadata filtering works but is not backwards compatible with existing namespaces code. 

### Are you interested in contributing this feature?

No

**Comment by miararoy** [comment]
Hi @shubhampatilappy !

Sorry for the late response 🙏

We are working on adding this very soon, right now aiming for api level setting of namespace 

Meaning the base api would be something like:

host:port/{namespace}/chat/completions

**Comment by MatthewTracy** [comment]
Heck yeah!
