### ISSUE TITLE
Can not install canopy with latest fastapi > 0.92.0?

### ISSUE THREAD

**Issue by hustxx** [pinecone-io/canopy#221]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [ ] I am requesting a straightforward extension of existing functionality

### Describe the feature

Our current application is running under fastapi 0.104.0, do I need to downgrade to 0.92.0 in order to install canopy? Can we loose the fastapi and uvicorn requirement here?

We do not need the server part of canopy, we want to use the library part to build our own service (I believe there should be many people have the same requirement?), is this possible?

**Comment by izellevy** [comment]
Hi @hustxx!

Currently, we don't support just using the library part, but we are planning to separate the components soon.

In the meantime, as a temporary fix we can loosen the requirements taking a small risk that the server might fail to launch if there are some breaking changes. 

I opened a PR here: https://github.com/pinecone-io/canopy/pull/229
