### ISSUE TITLE
[Feature] Allow For Other Ports Besides 8000

### ISSUE THREAD

**Issue by gfleetwood** [pinecone-io/canopy#230]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

It would be good if the user could choose which port to run canopy on. This works although it's undocumented;

```
canopy start --port 8002
```

But `canopy health` and `canopy chat` both still look for port 8000.

**Comment by igiloh-pinecone** [comment]
Hi @gfleetwood,

Thank you very much for your input!  
Please note that both `canopy health` and `canopy chat` take a `--url` argument (for `chat` it's called `--chat-server-url`, we'll change that to `--url` for uniformity). You can provide any url like `http://localhost:8002` or even a remote\cloud canopy server like `http://<my.server's.ip.addr>:<arbitrary_port>`.  
These optional arguments, just like the `--port` argument for `canopy server`, are documented in the docstring and CLI help message (`canopy chat --help`). How else do you believe they should be documented?

**Comment by gfleetwood** [comment]
@igiloh-pinecone Ah, I checked the cli and somehow missed the help flag. Sorry for bringing this up, now I see all the options.
