### ISSUE TITLE
CMake bug in pip installer for  canopy-sdk

### ISSUE THREAD

**Issue by gaoptimize** [pinecone-io/canopy#247]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The pip installer for canopy-sdk fails.

### Expected Behavior

I expect the pip installer to be work.

### Steps To Reproduce

In the command prompt run: python -m pip install canopy-sdk

### Relevant log output

```shell
Collecting sentencepiece<0.2.0,>=0.1.99 (from canopy-sdk)
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]

 CMake Deprecation Warning at CMakeLists.txt:15 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- VERSION: 0.1.99
      CMake Error at CMakeLists.txt:23 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLan
```

### Environment

```markdown
- **Windows 10**:
- **Python 3.12.1**:
- **Latest pip**:
- **CMake 3.28.1**:
```

### Additional Context

My suspicion is that sentencepiece-0.1.99.tar.gz needs an earlier version of CMake., or sentencepiece is essentially (currently) incompatible with Python 3.12.1.  See https://github.com/google/sentencepiece/issues/932 .

**Comment by izellevy** [comment]
@gaoptimize as stated before canopy currently has no support for Python 3.12. We are planning to add support for Python 3.12 in the upcoming months.
