### ISSUE TITLE
Error code: 400 [openai.BadRequestError] Context Length Exceeded

### ISSUE THREAD

**Issue by justice364** [pinecone-io/canopy#251]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I sent a user message and got an error on the 'Without Context (No RAG)' section in canopy chat. Error code: 400. Basically, the model's maximum context length was exceeded from user messages results in a canopy chat thread.

### Expected Behavior

With Context (RAG):

Yes, for a Dramatic clothing personality type in a casual wear setting with a Winter seasonal palette, purple can be a recommended color for sweaters or tops. The Winter palette includes colors like royal purple, which is a bright and bold shade of purple. Winter palettes strive to stay sharp and are best in clear and high-contrast colors, so a vibrant purple can be a great choice for a Dramatic personality type in casual wear. Source: 978-0345345462

Without Context (No RAG):

(OpenAI's response)

### Steps To Reproduce

1. canopy start (in one terminal)
2. canopy chat --no-rag (in a different terminal)
3. Send 12 user messages between 1-3 short sentences.
4. The 12th user message received the error.

### Relevant log output

```shell
Yes, for a Dramatic clothing personality type in a casual wear setting with a Winter seasonal palette, purple can be a recommended color for sweaters or tops. The Winter palette includes colors like royal purple, which is a bright and bold shade of purple. Winter palettes strive to stay sharp and are best in clear and high-contrast colors, so a vibrant purple can be a great choice for a Dramatic personality type in casual wear. Source: 978-0345345462
Traceback (most recent call last):
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\canopy_cli\cli.py", line 443, in _chat
    openai_response = client.chat.completions.create(
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_utils\_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\resources\chat\completions.py", line 648, in create
    return self._post(
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 1167, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 856, in request
    return self._request(
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_base_client.py", line 947, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 4097 tokens. However, your messages resulted in 4135 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\Scripts\canopy.exe\__main__.py", line 7, in <module>
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\canopy_cli\cli.py", line 577, in chat
    _ = _chat(
  File "C:\Users\J\AppData\Local\Programs\Python\Python310\lib\site-packages\canopy_cli\cli.py", line 447, in _chat
    err = e.http_body if isinstance(e, OpenAI_APIError) else str(e)
AttributeError: 'BadRequestError' object has no attribute 'http_body'
```

### Environment

```markdown
- **OS**: Windows 11
- **Language version**: Python 3.10
- **Canopy version**: 0.6.0
- **Terminal**: Windows Powershell
```

### Additional Context

I used the "canopy chat --no rag". The "With Context (RAG):" response sent accurate and fully. The error occurred on the " Without Context (No RAG):" part. 

I converted the JSONL file to text, and attached that for reference. I 'canopy upsert' the JSONL file to my canopy.

I'm using two instances of Windows Powershell; one for the server, one for the chat. Testing purposes.

OpenAI API key and Pinecone API key are set as Windows Environmental Variables.

I used my OpenAI API key. I haven't edited any OpenAI settings via Canopy (I don't know how).

[fashionadvice_test2.txt](https://github.com/pinecone-io/canopy/files/13962549/fashionadvice_test2.txt)

**Comment by igiloh-pinecone** [comment]
Hi @justice364, thank you very much for your feedback!

TBH - in the `--no-rag` mode, the CLI chatbot sends the chat request directly to OpenAI, without even processing it via Canopy server. So this error is actually coming directly from OpenAI.   
Unlike Canopy's chat mechanism, which incudes built-in history pruning - OpenAI's native API simply errors out for long conversations.

Having said that, we of course want Canopy CLI users to get the best possible experience. We will look into applying the history pruning logic in the CLI Chatbot itself, before sending it to OpenAI.

**Comment by justice364** [comment]
Thank you for the swift reply! @igiloh-pinecone

In the meantime, is there a way I can choose OpenAI GPT-4 model instead for a larger context limit?

**Comment by igiloh-pinecone** [comment]
@justice364 Definitely. The `--no-rag` option is automatically using the same model as Canopy server - so setting Canopy to use a certain model (e.g. `gpt-4`) would also be used by `no-rag`.  
To configure Canopy server: 
1. Download the [example config file](https://github.com/pinecone-io/canopy/blob/main/config/config.yaml) 
2. Edit your local copy of the config file - under `llm:` change the `model_name` param ([line 54](https://github.com/pinecone-io/canopy/blob/main/config/config.yaml#54)).
  Note that you should probably also change the `tokenizer: model_name` param (line 26) accordingly. This is not mandatory, but will provide better results.
3. Important note: Canopy enforces a hard limit on the context length, which can be configured to be tighter than the selected model's context window. This is deliberate, as it allows users to control their costs. This setting appears in the config under `chat_engine: max_prompt_tokens`, which defaults to `4096`.
  If you switch to a model with larger context window (e.g. GPT-4 with a window of 32k) - canopy would still enforce contexts to be shorter than the configured `max_prompt_tokens`. It is up to the user to decide if they want to change that value. 
  (To be clear - this parameter **does not** affect the `--no-rag` option, which as I mentioned is sent directly to OpenAI.)
4. Run canopy server with the `--config` param: 
   ```bash
   canopy start --config my_config_file.yaml
   ```

Now whenever chat with `--no-rag`, both the RAG and the NO RAG options will use the configured `model_name`.  

BTW - note that you don't have to switch to the very expensive `gpt-4` model. OpenAI also offers a `gpt-3.5-turbo-16k` model with 4 times more context than gpt-3.5, but much more economic than gpt-4.
