### ISSUE TITLE
[Bug] Canopy Server Cannot Specify Alternate Index

### ISSUE THREAD

**Issue by justice364** [pinecone-io/canopy#253]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I get an error when I starting my canopy server and specify an index name that differs from my INDEX_NAME environmental variable.

### Expected Behavior

The canopy server would start on the specified index name.

### Steps To Reproduce

1. Set INDEX_NAME environmental variable
2. Create two different indexes (indices?). One index name will match the INDEX_NAME environmental variable. The other will not.
3. Start canopy server: canopy start --index-name canopy--test

### Relevant log output

```shell
🚨 Note 🚨
For debugging only. To run the Canopy server in production, please use Docker with a Gunicorn server.
Error: Index name provided via --index-name 'canopy--test' does not match the index name provided via the INDEX_NAME environment variable 'test1'
```

### Environment

```markdown
- **OS**: Windows 11
- **Language version**: Python 3.10
- **Canopy version**: 0.6.0
- **Terminal**: Windows Powershell
```

### Additional Context

In the canopy help options, it says:
  --index-name TEXT       Index name, if not provided already as an
                          environment variable.

So I assume I can't use a different index than the one specified in the environment variable. But I want to make sure this is a feature, not a bug.

I confirmed the index name in the log is the same as index I created.

**Comment by igiloh-pinecone** [comment]
Hi @justice364 , thanks for the feedback!

This is indeed a deliberate safeguard in the code, to prevent users from accidentally misconfiguring the server.

Do you believe this behavior should be changed?

**Comment by justice364** [comment]
Hi @igiloh-pinecone,

I'm undecided about the feature. I could see the feature being used to differentiate indices, e.g. client information, business information, and personal information. I've read about the "namespace" feature in the wiki; which would solve that dilemma.

My only concern with that would be about security and permissions:

1) How do security and permissions work with namespaces and multiple users?
2) Can any namespace be restricted based on the organization user through Pinecone?
3) Would those permissions take place in Pinecone or through canopy?

Thanks

**Comment by igiloh-pinecone** [comment]
@justice364 let me clarify. The safeguard is simply around passing `--index-name` with one value while the `INDEX_NAME` env var has a different value. There is nothing preventing you from running two separate Canopy instances - as long as you pass the index name to them via the argument.  

As for supporting multiple users - the intended design is indeed to use namespaces. Say you have two namespaces, called 'client_a` and `client_b` respectfully. The API paths `/client_a/chat/completion` and `/client_b/chat/completion` would automatically be sent to the relevant namespace on Pinecone DB.  
On the Pinecone DB side - the operations done on a given namespace (e.g. query, fetch) are guaranteed to be completely segregated from the vectors  of any other namespace. However Canopy itself doesn't restrict which users can invoke which API path (or any API path for that matter) - that's up to to you to implement.

If you prefer to run two separate Canopy instances (on two different ports), each connected to a different index - that's still totally doable. Just don't use the `INDEX_NAME` env var at all, instead passing the `--index-name` argument to both servers. Note that in this case as well - it is up to to you to configure security, deciding which users can access which port.

**Comment by justice364** [comment]
Hi,

Understood. Thank you!
