### ISSUE TITLE
ModuleNotFoundError: No module named 'canopy_cli.app'

### ISSUE THREAD

**Issue by kowshik24** [pinecone-io/canopy#255]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The gunicorn app name is incoreect may:
gunicorn canopy_cli.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers <number of desired worker processes>

### Expected Behavior

gunicorn canopy_server.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers <number of desired worker processes>

### Steps To Reproduce

1. change the gunicorn canopy_cli.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers <number of desired worker processes>
2. To gunicorn canopy_server.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers <number of desired worker processes>

### Relevant log output

```shell
ModuleNotFoundError: No module named 'canopy_cli.app'
```

### Environment

```markdown
- **OS**: Ubuntu 20.04.6
- **Language version**: python3.10
- **Canopy version**: canopy-sdk==0.6.0
```

### Additional Context

gunicorn canopy_cli.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers <number of desired worker processes>

**Comment by miararoy** [comment]
hi @kowshik24 thanks for flagging, fixed!

**Comment by miararoy** [comment]
closing this
